//
//  Contact.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers class Contact: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _number: String?
    var _name: String?
    
    class func dynamoDBTableName() -> String {
        
        return "demoheisenberg-mobilehub-2147232062-Contact"
    }
    
    class func hashKeyAttribute() -> String {
        
        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {
        
        return "_number"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "_userId" : "userId",
            "_number" : "number",
            "_name" : "name",
        ]
    }
}
